api: 
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: secure
          scheme: https

  secure:
    address: ":443"

providers:
    file:
      filename: ./dynamic.yml
    docker:
        exposedByDefault: false
        network: proxy